async(page)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/src/main.ts*',async route=>{const r=await route.fetch();await route.fulfill({response:r,body:(await r.text())+'\nwindow.__qa=game;'});});await page.setViewportSize({width:1280,height:850});await page.reload();
 try{
 await page.getByRole('button',{name:'PIDALF, THE SLOP SLAYER, FORCE / COMPACTION',exact:true}).click();
 await page.screenshot({path:'output/playwright/pidalf-roster-v29.png'});
 const alpha=await page.evaluate(async()=>{const im=new Image();im.src='/assets/pidalf-intro-v2.png';await im.decode();const c=document.createElement('canvas');c.width=im.width;c.height=im.height;const ctx=c.getContext('2d');ctx.drawImage(im,0,0);return {corner:ctx.getImageData(0,0,1,1).data[3],center:ctx.getImageData(im.width/2,im.height/2,1,1).data[3]};});if(alpha.corner!==0||alpha.center===0)throw Error('Portrait alpha incorrect '+JSON.stringify(alpha));
 const result=await page.evaluate(()=>{
  const g=window.__qa;cancelAnimationFrame(g.frame);const assert=(v,m)=>{if(!v)throw Error(m);};let point={x:300,y:820};
  const setup=()=>{g.selectCharacter('pidalf');g.start();g.finishIntro();g.barks.clear();g.audio.setMuted(true);g.effects=false;g.world.blocks.fill(null);for(let x=0;x<100;x++)for(let y=43;y<50;y++)g.world.set(x,y,3);g.enemies=[];g.barrels=[];g.relays=[];g.rescues=[];g.alarms=[];g.boss.active=false;g.player.x=170;g.player.y=828;g.cam=0;g.camY=440;g.aimPoint=()=>point;g.pointer.active=false;g.invuln=999;g.freeze=0;};
  const spawn=(x,y=830,type='gunner')=>{const e=g.spawnEnemy(x,y,type);e.cool=99;g.enemies.push(e);return e;};
  const step=(t)=>{for(let i=0;i<Math.ceil(t*120);i++)g.update(1/120);};
  setup();let e=spawn(290);point={x:470,y:845};g.press('KeyJ');step(.15);g.release('KeyJ');assert(!e.dead&&g.pidalfKit.waves.length,'Slop should travel before hitting');step(.25);assert(e.dead,'Slop did not kill ordinary bot');assert(g.debris.pieces.length>0,'No armor debris');
  setup();e=spawn(290,830,'shield');point={x:300,y:845};g.shoot();step(.4);assert(!e.dead&&e.shield===0,'Heavy enemy should lose armor first');step(.6);point={x:e.x+10,y:e.y+15};g.shoot();step(.45);assert(e.dead,'Second slap did not finish shield bot');
  setup();e=spawn(330);for(let y=37;y<43;y++)g.world.set(15,y,3);point={x:340,y:845};g.shoot();step(.7);assert(!e.dead,'Slop penetrates wall');g.press('KeyE');assert(g.pidalfKit.grabbing,'Grab should work through cover');point={x:250,y:845};step(.4);assert(e.x>=320,'Grabbed bot phased through wall');g.release('KeyE');point={x:e.x+10,y:e.y+15};g.press('KeyF');g.release('KeyF');assert(!g.pidalfKit.crush&&!e.dead,'Compact must respect cover');
  setup();e=spawn(290);point={x:300,y:845};g.press('KeyE');assert(g.pidalfKit.held.length===1,'E did not grab');for(let i=0;i<45;i++){point={x:300+i*2,y:840-i*2};step(1/120);}assert(e.y<810,'Grab did not lift body');g.release('KeyE');assert(e.vx>100&&e.vy< -100,'Release lost yank momentum');assert(Math.abs(e.vx)<=980&&Math.abs(e.vy)<=850,'Throw exceeds bounded speed');
  setup();e=spawn(290);point={x:300,y:845};g.press('KeyE');step(3.4);assert(!g.pidalfKit.grabbing&&g.pidalfKit.grabCooldown>0,'Hold is unbounded');g.release('KeyE');
  setup();e=spawn(290);point={x:300,y:845};g.press('KeyF');g.release('KeyF');assert(g.pidalfKit.crush,'Compact did not begin');step(.8);assert(e.dead&&g.pidalfKit.props.length===1,'Compact does not create prop');let prop=g.pidalfKit.props[0];assert(!prop.round&&prop.mass===1,'Low scale should create cube');point={x:prop.x+9,y:prop.y+9};g.press('KeyE');assert(g.pidalfKit.held[0]?.body===prop,'Cube cannot be grabbed');g.release('KeyE');
  setup();g.setThinking(2);const es=[spawn(280),spawn(320),spawn(365)];point={x:330,y:820};g.press('KeyF');g.release('KeyF');step(1.6);assert(es.every(e=>e.dead),'Large compaction did not collect squad');prop=g.pidalfKit.props[0];assert(prop?.round&&prop.mass===3,'Large compaction should create heavy ball');assert(!g.world.overlaps(prop.x,prop.y,prop.w,prop.h),'Prop spawned inside ground');
  const victim=spawn(460);prop.x=410;prop.y=860-prop.h;prop.vx=600;prop.vy=0;step(.12);assert(victim.dead||victim.hp<4,'Thrown ball did not damage bot');
  setup();e=spawn(290);point={x:300,y:845};g.press('KeyE');g.pause();assert(!g.pidalfKit.grabbing,'Pause retains grab');g.resume();assert(e.vx===0,'Pause threw held bot');g.die();assert(!g.pidalfKit.props.length&&!g.pidalfKit.crush,'Death retains ability state');g.respawn();assert(g.pidalfKit.grabCooldown===0,'Respawn does not reset kit');
  setup();g.relays=[{x:200,y:828,done:false,supplied:true}];g.press('KeyE');assert(g.relays[0].done,'Pidalf cannot open mission uplink');g.release('KeyE');g.hud();assert(document.querySelector('.name').textContent==='PIDALF','Wrong HUD');assert(document.querySelector('#defense-ready').textContent==='Q REPEL','Repel missing from HUD');
  setup();e=spawn(240);point={x:250,y:845};const bullet={x:310,y:838,vx:-260,vy:0,life:2,hostile:true,power:2,pierce:0,boost:false,tier:0,hit:new Set()};g.bullets.push(bullet);g.press('KeyQ');g.release('KeyQ');step(.32);assert(e.vx>200,'Repel did not push bot away');assert(!bullet.hostile&&bullet.vx>0,'Repel did not redirect projectile');assert(g.pidalfKit.qCooldown>4,'Repel has no recovery');
  setup();point={x:600,y:845};assert(g.pidalfKit.aimGuide().range,'No range feedback');point={x:340,y:845};e=spawn(330);for(let y=37;y<43;y++)g.world.set(15,y,3);assert(g.pidalfKit.aimGuide().blocked&&g.pidalfKit.aimGuide().wall,'No cover feedback');point={x:260,y:845};e=spawn(250);assert(g.pidalfKit.aimGuide().valid,'Valid aim not recognized');
  setup();const barrel={x:290,y:830,w:18,h:30,vx:0,vy:0,grounded:false,hp:2,dead:false,fuse:0};g.barrels.push(barrel);point={x:299,y:845};assert(g.pidalfKit.aimGuide().barrel===barrel,'Barrel has no targeting feedback');g.press('KeyE');assert(g.pidalfKit.held[0]?.body===barrel,'Cannot grab barrel');for(let i=0;i<45;i++){point={x:300+i*2,y:840-i*2};step(1/120);}assert(barrel.y<810&&!barrel.dead&&!barrel.fuse,'Lifting barrel should not ignite it');g.release('KeyE');assert(barrel.vx>100&&barrel.vy<0,'Barrel lost throwing momentum');for(let y=30;y<43;y++)g.world.set(25,y,3);step(1);assert(barrel.dead,'Thrown barrel did not explode on impact');
  setup();const heldBomb={x:290,y:830,w:18,h:30,vx:0,vy:0,grounded:false,hp:2,dead:false,fuse:.15};g.barrels.push(heldBomb);point={x:299,y:845};g.press('KeyE');step(.3);assert(heldBomb.dead&&!g.pidalfKit.held.length,'Held burning barrel must still explode and release');g.release('KeyE');
  const distances=[];for(const power of [0,1,2]){setup();g.setThinking(power);point={x:510,y:800};g.pidalfKit.strike({x:510,y:800,scale:power/2});g.pidalfKit.updateWaves(.1);distances.push(g.pidalfKit.waves[0].travel);}assert(distances[0]>distances[1]&&distances[1]>distances[2]&&distances[0]>distances[2]*2.8,'Small wave must be substantially faster, continuously');
  setup();e=spawn(290);point={x:323,y:845};g.pidalfKit.compact();assert(!g.pidalfKit.crush,'Small compact must not select a nearby bot');point={x:300,y:845};g.pidalfKit.compact();assert(g.pidalfKit.crush?.targets[0]===e,'Small compact must select bot under cursor');
  setup();g.setThinking(2);point={x:400,y:780};g.pidalfKit.compact();assert(g.pidalfKit.crush?.x===400&&g.pidalfKit.crush?.y===780&&!g.pidalfKit.crush.targets.length,'Large compact must create a black hole at empty cursor position');e=spawn(405,770);step(.2);assert(g.pidalfKit.crush.targets.includes(e),'Black hole must gather bots entering its area');step(1.4);assert(e.dead&&g.pidalfKit.props[0]?.round,'Gathered bot must become rolling scrap');
  setup();g.setThinking(2);point={x:250,y:790};for(let y=35;y<43;y++)g.world.set(15,y,3);e=spawn(330,790);g.pidalfKit.compact();step(.3);assert(g.pidalfKit.crush&&!g.pidalfKit.crush.targets.includes(e),'Black hole must not gather through cover');point={x:340,y:805};const guide=g.pidalfKit.aimGuide();assert(guide.grabValid&&!guide.compactValid,'Guide should distinguish grab and compact through cover');
  setup();g.barks.gap=0;point={x:480,y:800};g.pidalfKit.strike({x:480,y:800,scale:0});assert(g.barks.active?.event==='shockwave','Shockwave must use normal speech bubbles');const firstLine=g.barks.active.line;g.pidalfKit.strike({x:480,y:800,scale:0});assert(g.barks.active.line===firstLine&&!g.barks.pending,'Shockwave spam must obey dialogue pacing');g.barks.update(26);g.pidalfKit.strike({x:480,y:800,scale:0});assert(g.barks.active.line!==firstLine,'Shockwave lines must vary');
  setup();const grenade={x:300,y:815,vx:0,vy:0,life:1.7};g.grenades.push(grenade);point={x:300,y:815};g.press('KeyE');assert(g.pidalfKit.held[0]?.grenade===grenade,'Cannot grab grenade');for(let i=0;i<24;i++){point={x:300+i*3,y:815-i*2};step(1/120);}assert(grenade.y<805&&grenade.life<1.7,'Held grenade must move while fuse burns');g.release('KeyE');assert(grenade.vx>100&&grenade.vy<0,'Grenade lost yank velocity');
  setup();const incoming={x:270,y:830,vx:-180,vy:0,life:1.7};g.grenades.push(incoming);point={x:500,y:830};g.pidalfKit.strike({x:500,y:830,scale:0});g.pidalfKit.updateWaves(.1);assert(incoming.vx>400&&incoming.vy<0&&incoming.life===1.7,'Shockwave should push grenade without resetting fuse');
  setup();g.world.set(15,41,2);point={x:310,y:830};assert(g.pidalfKit.aimGuide().crate,'Crate has no targeting hint');g.press('KeyE');let crate=g.pidalfKit.held[0]?.body;assert(crate?.crate&&!g.world.get(15,41),'Grab must detach actual crate tile');point={x:370,y:750};step(.18);g.release('KeyE');assert(crate.vx>100,'Crate cannot be thrown');
  setup();g.world.set(15,41,2);point={x:500,y:830};g.pidalfKit.strike({x:500,y:830,scale:0});g.pidalfKit.updateWaves(.15);crate=g.pidalfKit.props.find(p=>p.crate);assert(crate&&crate.vx>400&&!g.world.get(15,41),'Shockwave should push crate intact');
  setup();g.world.set(12,41,2);g.pidalfKit.repel();crate=g.pidalfKit.props.find(p=>p.crate);assert(crate&&crate.vx>0&&!g.world.get(12,41),'Staff slam should loosen and push crate');
  setup();g.barks.gap=0;g.pidalfKit.repel();assert(g.barks.active?.event==='repel'&&g.pidalfKit.messageLife===0,'Staff slam must use normal dialogue, not special text');const repelLine=g.barks.active.line;g.barks.update(26);g.pidalfKit.repel();assert(g.barks.active.line!==repelLine,'Staff slam quips must rotate');
  setup();e=spawn(330);for(let y=40;y<43;y++)g.world.set(15,y,3);point={x:340,y:845};g.press('KeyE');g.shoot();assert(!g.pidalfKit.crush&&g.pidalfKit.grabbing,'Blocked held target must remain held without compacting');point={x:340,y:725};step(.55);assert(g.pidalfKit.visible(e),'Dragged target should clear cover');g.shoot();assert(g.pidalfKit.crush?.fromGrab&&!g.pidalfKit.slap,'Click while grabbing must compact the held target');step(.8);prop=g.pidalfKit.props[0];assert(e.dead&&g.pidalfKit.grabbing&&g.pidalfKit.held.some(h=>h.body===prop),'Compacted scrap must remain held');for(let i=0;i<20;i++){point={x:340+i*4,y:725-i};step(1/120);}g.release('KeyE');assert(!g.pidalfKit.grabbing&&prop.vx>100,'Release E must throw compacted scrap');
  setup();e=spawn(290);point={x:300,y:845};g.press('KeyE');g.shoot();g.release('KeyE');step(.8);assert(e.dead&&!g.pidalfKit.grabbing&&!g.pidalfKit.held.length,'Releasing E mid-crush must not regrab on completion');
  setup();e=spawn(290);point={x:300,y:845};g.press('KeyE');g.shoot();g.pause();g.resume();step(.8);assert(!g.pidalfKit.grabbing&&!g.pidalfKit.held.length,'Pause mid-crush must cancel automatic carry');
  // Render repeatable showcase captures next.
  setup();g.setThinking(2);spawn(290);spawn(340);spawn(380);point={x:345,y:802};g.press('KeyF');g.release('KeyF');step(.7);g.cam=0;g.camY=440;g.render();g.hud();
  return {mechanics:'passed',snapshot:g.pidalfKit.snapshot()};
 });
 await page.screenshot({path:'output/playwright/pidalf-compact-v29.png'});
 await page.evaluate(()=>{const g=window.__qa;for(let i=0;i<120;i++)g.update(1/120);g.cam=0;g.camY=440;g.render();g.hud();});
 await page.screenshot({path:'output/playwright/pidalf-ball-v29.png'});
 if(errors.length)throw Error(errors.join('\n'));return {result,errors};
 }finally{await page.unroute('**/src/main.ts*');await page.reload();}
}
