async(page)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/src/main.ts*',async route=>{const r=await route.fetch();await route.fulfill({response:r,body:(await r.text())+'\nwindow.__qa=game;'});});await page.setViewportSize({width:1440,height:960});await page.reload();
 try{
 const checks=await page.evaluate(()=>{
  const g=window.__qa;cancelAnimationFrame(g.frame);g.audio.setMuted(true);g.selectCharacter('marcus');const results=[],assert=(v,m)=>{if(!v)throw Error(m);};let aim;
  const setup=()=>{g.start();g.finishIntro();g.audio.setMuted(true);g.effects=false;g.world.blocks.fill(null);for(let x=0;x<70;x++)g.world.set(x,43,3);g.enemies=[];g.barrels=[];g.alarms=[];g.relays=[];g.rescues=[];g.encounters.update=()=>{};g.boss.active=false;g.player.x=150;g.player.y=828;g.invuln=100;g.cam=0;g.camY=440;g.setThinking(2);g.barks.clear();g.fireTimer=0;aim={x:310,y:840};g.aimPoint=()=>aim;g.updateAim=()=>{g.aimAngle=Math.atan2(aim.y-g.player.y-15,aim.x-g.player.x-10);g.face=Math.cos(g.aimAngle)>=0?1:-1;g.aim=Math.atan2(Math.sin(g.aimAngle),Math.cos(g.aimAngle)*g.face);};return g.marcusKit;};
  const tick=(k,n=1)=>{for(let i=0;i<n;i++){g.time+=1/120;g.fireTimer-=1/120;k.update(1/120);}};
  const until=(k,fn)=>{for(let i=0;i<500&&!fn();i++)tick(k);assert(fn(),'timed out awaiting chomp');};
  const enemy=(x,y=830,type='gunner',hp=4)=>{const e=g.spawnEnemy(x,y,type,-1);e.hp=e.max=hp;g.enemies.push(e);return e;};
  let k=setup();assert(k.mode===3&&k.name==='PAC-MAN','third cartridge selected');let targets=[enemy(305),enemy(385,710,'drone'),enemy(480),enemy(570,750,'drone')];aim={x:315,y:845};k.fireInput(.01,true);assert(k.pacman.active&&k.stock===3,'launch occupies one stock');const launched=k.pacman.launched;for(let i=0;i<15;i++)k.fireInput(.01,true);assert(k.pacman.launched===launched,'holding never repeats');k.fireInput(.01,false);
  for(let i=0;i<4;i++){until(k,()=>k.pacman.active?.phase==='bite'&&k.pacman.active.chain===i+1);assert(k.pacman.controls(targets[i]),'bite takes visual control before damage');tick(k,24);if(i<3){aim={x:targets[i+1].x+10,y:targets[i+1].y+15};k.fireInput(.01,true);assert(k.pacman.active.queued===targets[i+1],'click selects next target');k.fireInput(.01,false);}}
  tick(k,70);assert(k.pacman.bites===4&&k.pacman.finishers===1&&!k.pacman.active,'four bites end in one finisher');assert(targets.every(e=>e.dead)&&k.stock===4,'kills and stock restored');results.push('four-target vertical chain, one-shot input, fourth crunch and refund');
  k=setup();let e=enemy(300,830,'turret',50);aim={x:310,y:845};k.pacman.click();until(k,()=>k.pacman.active?.phase==='bite');tick(k,24);const hp=e.hp;k.pacman.click();assert(!k.pacman.active.queued,'cannot bite same bot twice');tick(k,120);assert(k.pacman.bites===1&&e.hp===hp&&!k.pacman.active,'no click ends after one bite without repeat damage');results.push('no automatic chaining or repeat hits');
  k=setup();e=enemy(300,830,'turret',30);const comboTarget=enemy(420,730,'turret',30);aim={x:310,y:845};k.pacman.click();until(k,()=>k.pacman.active?.phase==='bite');tick(k,12);aim={x:430,y:745};k.pacman.click();tick(k,10);assert(e.hp===25,'queued timing bonus does not affect current bite');until(k,()=>k.pacman.active?.chain===2);tick(k,24);assert(comboTarget.hp===22,'timing bonus affects next bite exactly once');results.push('queued timing bonus');
  k=setup();e=enemy(330);for(let y=25;y<43;y++)g.world.set(14,y,3);aim={x:340,y:845};k.pacman.click();tick(k,180);assert(e.hp===4&&!k.pacman.active,'solid wall blocks acquisition and physical projectile');assert(k.stock===4,'wall refunds stock');results.push('steel blocking and miss cleanup');
  k=setup();e=enemy(300);const next=enemy(410,730,'drone');aim={x:310,y:845};k.pacman.click();until(k,()=>k.pacman.active?.phase==='bite');tick(k,24);aim={x:420,y:745};k.pacman.click();next.dead=true;tick(k,140);assert(!k.pacman.active&&k.stock===4,'lost queued target safely ends');results.push('dead queued target');
  k=setup();e=enemy(300,830,'shield',30);aim={x:310,y:845};k.pacman.click();until(k,()=>k.pacman.active?.phase==='bite');tick(k,24);assert(e.shield===3&&e.hp===25,'normal bite damages but does not one-shot heavy armor');k.recall();assert(!k.pacman.active&&k.stock===4,'E cancels chomp');results.push('armor and recall');
  k=setup();e=enemy(300);k.pacman.click();const x=k.pacman.active.x;g.pause();g.update(.4);assert(k.pacman.active.x===x,'pause freezes projectile');g.resume();g.setThinking(0);tick(k,180);assert(!k.pacman.active,'mode switch allows finite projectile to finish');g.setThinking(2);g.fireTimer=0;k.pacman.cooldown=0;k.pacman.click();g.die();assert(!k.pacman.active&&k.stock===4,'death clears active');results.push('pause, switch, death lifecycle');
  k=setup();g.press('Digit4');assert(k.mode===3,'4 key selects Pac-Man');g.selectCharacter('tibo');g.setThinking(2);assert(g.thinking===2,'other heroes remain three-mode');g.selectCharacter('marcus');g.setThinking(2);g.hud();assert(document.querySelector('#thinking-slider').value==='100','four-mode HUD normalized');results.push('three-cartridge selection and slider');
  k=setup();targets=[enemy(315),enemy(410,720,'drone'),enemy(480),enemy(550,760,'drone')];aim={x:325,y:845};k.pacman.click();until(k,()=>k.pacman.active?.phase==='bite');tick(k,25);aim={x:420,y:735};g.modeFeedback=0;g.toastTimer=0;document.querySelector('.toast').innerHTML='';g.hud();g.render();window.__pacTargets=targets;return results;
 });
 await page.screenshot({path:'output/playwright/marcus-pacman-chain-v34.png'});
 const input=await page.evaluate(()=>{const g=window.__qa,k=g.marcusKit,targets=window.__pacTargets;g.pointer.down=true;g.update(1/120);g.pointer.down=false;g.update(1/120);if(!k.pacman.active?.queued)throw Error('production click failed to chain');return {mode:k.mode,queued:true,stats:k.pacman.snapshot()};});
 await page.evaluate(()=>{const g=window.__qa,k=g.marcusKit,targets=window.__pacTargets;g.invuln=0;const tick=()=>{g.time+=1/120;g.fireTimer-=1/120;k.update(1/120);};for(let i=0;i<600;i++){const p=k.pacman.active;if(!p)break;if(p.phase==='bite'&&p.chain===4&&p.damaged)break;if(p.phase==='bite'&&p.chain<4&&p.age>.2&&!p.queued){const e=targets[p.chain];g.aimPoint=()=>({x:e.x+10,y:e.y+15});k.pacman.click();}tick();}if(k.pacman.finishers!==1)throw Error('finisher capture failed');g.hud();g.render();});
 await page.screenshot({path:'output/playwright/marcus-pacman-crunch-v34.png'});
 if(errors.length)throw Error(errors.join('\n'));return {checks,input,errors};
 }finally{await page.unroute('**/src/main.ts*');await page.reload();}
}
