async(page)=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/src/main.ts*',async route=>{const r=await route.fetch();await route.fulfill({response:r,body:(await r.text())+'\nwindow.__qa=game;'});});await page.setViewportSize({width:1440,height:960});await page.reload();
 try{
 const checks=await page.evaluate(()=>{
  const g=window.__qa;cancelAnimationFrame(g.frame);g.audio.setMuted(true);g.selectCharacter('marcus');const results=[],assert=(v,m)=>{if(!v)throw Error(m);};
  const setup=()=>{g.start();g.finishIntro();g.audio.setMuted(true);g.effects=false;g.world.blocks.fill(null);for(let x=0;x<70;x++)g.world.set(x,43,3);g.enemies=[];g.barrels=[];g.alarms=[];g.relays=[];g.rescues=[];g.encounters.update=()=>{};g.player.x=150;g.player.y=828;g.invuln=0;g.cam=0;g.camY=440;g.setThinking(1);g.barks.clear();g.aimPoint=()=>({x:550,y:844});g.updateAim=()=>{const a=g.aimPoint();g.aimAngle=Math.atan2(a.y-g.player.y-16,a.x-g.player.x-10);g.face=Math.cos(g.aimAngle)>=0?1:-1;g.aim=Math.atan2(Math.sin(g.aimAngle),Math.cos(g.aimAngle)*g.face);};return g.marcusKit;};
  const charge=(k,n=80)=>{for(let i=0;i<n;i++)k.lcd.input(1/120,true,i===0);};
  const fly=(k,n=60)=>{for(let i=0;i<n;i++){k.update(1/120);if(k.lcd.driving)k.lcd.move(1/120);g.fireTimer-=1/120;}};
  let k=setup();charge(k);assert(k.lcd.charging&&!k.lcd.flight&&g.player.x===150,'hold is windup');assert(!k.lcd.visible,'windup keeps Marcus human');k.lcd.input(1/120,false,false);assert(k.lcd.flight&&k.lcd.visible,'release transforms into LCD flight');g.damage();assert(g.health===3,'flight blocks damage');fly(k);assert(g.player.x>450&&g.player.x<500,'aimed short launch range');assert(k.lcd.airUsed&&!k.lcd.flight,'one air launch');assert(k.lcd.land>1.5&&k.lcd.visible,'LCD form lingers on arrival');g.damage();assert(g.health===2,'vulnerability returns');charge(k);assert(!k.lcd.charging,'cannot relaunch midair');results.push('charge, launch, range, flight protection, air limit');
  k=setup();let e=g.spawnEnemy(295,830,'shield',-1);e.hp=20;g.enemies=[e];charge(k);k.lcd.input(1/120,false,false);fly(k);assert(k.lcd.hits===1&&e.hp===12,'one damage event per enemy');assert(e.vx>700&&e.vy<0&&e.shield===0,'shield strip and strong directional fling');results.push('shield impact and knockback');
  k=setup();for(let y=39;y<43;y++)g.world.set(14,y,3);e=g.spawnEnemy(315,830,'gunner',-1);g.enemies=[e];charge(k);k.lcd.input(1/120,false,false);fly(k);assert(g.player.x<=260.01&&!g.world.overlaps(g.player.x,g.player.y,20,32),'steel stops body');assert(e.hp===4,'no kick through steel');results.push('steel collision and occlusion');
  k=setup();for(let y=41;y<43;y++)g.world.set(14,y,2);charge(k);k.lcd.input(1/120,false,false);fly(k);assert(g.world.destroyed===2&&g.player.x>300,'charged kick breaks crates');results.push('crate breach');
  k=setup();g.aimPoint=()=>({x:160,y:520});charge(k);k.lcd.input(1/120,false,false);fly(k);assert(g.player.y<550,'vertical traversal');results.push('upward launch');
  k=setup();g.player.y=650;g.player.grounded=false;charge(k);for(let i=0;i<20;i++)k.lcd.move(1/120);assert(g.player.y===650&&g.player.vy===0,'charging freezes in midair');g.pause();assert(!k.lcd.charging,'pause cancels charge');g.resume();k.wasFiring=false;charge(k);g.setThinking(0);assert(k.lcd.charging,'scroll must preserve movement charge');results.push('air hold and input cancellation');
  k=setup();g.player.y=650;g.player.grounded=false;g.time=10;k.lcd.sampleBody();const heldY=k.lcd.drawY;g.player.y=640;g.time+=1/60;k.lcd.sampleBody();assert(k.lcd.drawY===heldY,'jump drawing holds its LCD position');g.time+=.09;k.lcd.sampleBody();assert(k.lcd.drawY===656,'jump drawing steps to next position');results.push('discrete jump positions');
  k=setup();charge(k);g.press('KeyQ');assert(!k.lcd.charging&&k.flip>0,'Q cancels windup');results.push('dodge cancel');
  k=setup();charge(k);k.lcd.input(1/120,false,false);fly(k);for(let i=0;i<150;i++)g.update(1/120);assert(g.player.grounded&&!k.lcd.airUsed,'landing reloads');charge(k);assert(k.lcd.charging,'can launch after landing and recovery');k.lcd.input(1/120,false,false);g.die();assert(!k.lcd.flight&&!k.lcd.charging,'death cleans up');results.push('landing recovery and death cleanup');
  k=setup();charge(k);g.modeFeedback=0;g.toastTimer=0;document.querySelector('.toast').innerHTML='';g.hud();g.render();return results;
 });
 await page.screenshot({path:'output/playwright/marcus-lcd-charge-v33.png'});
 await page.evaluate(()=>{const g=window.__qa,k=g.marcusKit;g.enemies=[g.spawnEnemy(340,830,'shield',-1),g.spawnEnemy(430,830,'gunner',-1)];k.lcd.input(1/120,false,false);for(let i=0;i<17;i++){g.time+=1/120;k.update(1/120);if(k.lcd.driving)k.lcd.move(1/120);}g.hud();g.render();});
 await page.screenshot({path:'output/playwright/marcus-lcd-kick-v33.png'});
 // Production input / movement integration, not just the isolated flight driver.
 const input=await page.evaluate(()=>{const g=window.__qa;g.start();g.finishIntro();g.setThinking(1);g.invuln=100;g.press('Space');for(let i=0;i<8;i++)g.update(1/120);g.release('Space');g.press('Space');for(let i=0;i<85;i++)g.update(1/120);const charged=g.marcusKit.lcd.charging;g.release('Space');g.update(1/120);const started=!!g.marcusKit.lcd.flight;for(let i=0;i<55;i++)g.update(1/120);if(!charged||!started||g.player.x<200)throw Error('production input/flight failed');const launchX=g.player.x;g.start();g.finishIntro();g.setThinking(1);g.invuln=100;g.player.y=600;g.player.vy=400;g.player.grounded=false;g.press('Space');for(let i=0;i<42;i++)g.update(1/120);const heldY=g.player.y;for(let i=0;i<120;i++)g.update(1/120);if(g.player.y!==heldY||g.player.vy!==0)throw Error('production air hold failed');g.release('Space');g.update(1/120);if(!g.marcusKit.lcd.flight)throw Error('air hold release failed');return {charged,started,x:launchX,airHold:true,lcd:g.marcusKit.lcd.snapshot()};});
 if(errors.length)throw Error(errors.join('\n'));return {checks,input,errors};
 }finally{await page.unroute('**/src/main.ts*');await page.reload();}
}
