async(page)=>{
 await page.setViewportSize({width:1280,height:720});
 const errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('**/src/main.ts*',async route=>{const r=await route.fetch();await route.fulfill({response:r,body:(await r.text())+'\nwindow.__qa=game;'});});
 await page.reload();await page.waitForFunction(()=>window.__qa?.rosterPreview);
 try{
 await page.locator('[data-bro="theo"]').click();
 await page.screenshot({path:'output/playwright/theo-roster.png'});
 const results=await page.evaluate(()=>{
  const g=window.__qa;cancelAnimationFrame(g.frame);g.rosterPreview.paused=true;const assert=(v,m)=>{if(!v)throw Error(m);};const results=[];let k;
  const setup=(mode=0)=>{g.selectCharacter('theo');g.start();g.finishIntro();g.audio.muted=true;g.effects=false;g.keys.clear();g.pointer.down=false;g.world.blocks.fill(null);for(let x=0;x<204;x++)for(let y=43;y<50;y++)g.world.set(x,y,3);Object.assign(g.player,{x:160,y:828,vx:0,vy:0,grounded:true});g.enemies=[];g.barrels=[];g.relays=[];g.rescues=[];g.alarms=[];g.bullets=[];g.boss.active=false;g.setThinking(mode);k=g.theoKit;g.aimPoint=()=>({x:900,y:844});g.updateAim=()=>{g.face=1;g.aim=0;g.aimAngle=0;};g.invuln=100;};
  const tick=(t,world=false)=>{for(let i=0;i<Math.ceil(t*120);i++){g.updateActor(1/120);if(world)g.updateWorld(1/120);}};
  setup();assert(!k.riding&&k.attached,'Must start carrying the board');g.setThinking(2);assert(!k.riding,'Scroll must not mount');g.press('KeyD');tick(.28);assert(k.mounted&&k.mountBlend>0&&k.mountBlend<1,'Drop-and-mount transition missing');tick(.42);assert(g.player.vx>400&&k.riding,'Ride acceleration missing');g.release('KeyD');const speed=g.player.vx;tick(.2);assert(g.player.vx>speed*.65,'Coasting loses momentum too quickly');tick(1);assert(!k.riding&&k.attached,'Slow down should pick up the deck');results.push('automatic mount / coast / pickup');
  setup();g.player.vx=450;g.keys.add('KeyD');k.launch();tick(.12);assert(g.player.vx===260,'Away-board movement must use running speed');g.release('KeyD');tick(.15);assert(g.player.vx===0,'Without board Theo must stop on release');g.press('KeyA');tick(.1);assert(g.player.vx===-260,'Without board direction changes must be responsive');results.push('on-foot speed / stopping / reversal');
  setup();g.player.vx=450;g.keys.add('KeyD');k.mounted=true;k.mountBlend=1;const ram=g.spawnEnemy(192,830,'gunner');ram.hp=8;g.enemies=[ram];tick(.04);assert(k.rams===1&&ram.hp<8&&ram.vx>600,'Fast skating did not ram / launch bot');assert(g.player.vx>410,'Light ram killed the skating line');results.push('high-speed skating ram');
  setup();g.player.vx=160;const slow=g.spawnEnemy(185,830,'gunner');g.enemies=[slow];tick(.04);assert(k.rams===0&&slow.hp===4,'Slow skating should not gain ram damage');results.push('ram speed threshold');
  setup();g.player.vx=300;k.mounted=true;k.mountBlend=1;const a=g.spawnEnemy(300,830,'gunner'),b=g.spawnEnemy(400,830,'gunner');a.hp=b.hp=6;g.enemies=[a,b];k.launch();assert(!k.attached&&g.player.vy<0,'Kick-off failed');for(let i=0;i<120;i++)k.update(1/120);assert(k.carries>0,'Deck never carried a light bot');assert(k.crashes>0&&g.kills>0,'Carried bot did not crash into next bot');assert(!k.passenger,'Passenger remained stuck after crash');results.push('kick-off / carry / crash');
  k.recall();for(let i=0;i<240&&!k.attached;i++)k.update(1/120);assert(k.attached&&k.catches===1,'Deck recall failed');assert(k.board.state==='attached','Recall created duplicate or lost deck');results.push('recall and catch');
  setup();g.player.vx=330;g.keys.add('KeyD');k.launch();k.board.x=650;k.board.y=843;k.recall();for(let i=0;i<240&&!k.attached;i++)k.update(1/120);assert(k.attached&&g.player.vx>0,'Recall from ahead reversed the rider');results.push('forward recall catch');
  setup();k.launch();k.board.x=650;k.board.y=843;const returning=g.spawnEnemy(390,828,'gunner');returning.hp=20;g.enemies=[returning];k.recall();for(let i=0;i<240&&!k.attached;i++)k.update(1/120);assert(returning.hp<20&&k.returnHits===1,'Return should hit each bot once');assert(g.player.vx===0,'Stationary recall must not launch the player');results.push('return damage / stationary catch');
  setup();const heavy=g.spawnEnemy(300,830,'shield');heavy.hp=20;g.enemies=[heavy];k.launch();for(let i=0;i<55;i++)k.update(1/120);assert(!k.passenger&&heavy.hp<20&&heavy.shieldDown>0,'Heavy bot should be shoved and guard broken, not carried');results.push('heavy armor response');
  setup();const close=g.spawnEnemy(195,830,'gunner');close.hp=4;g.enemies=[close];k.fireInput(0,true);k.fireInput(0,false);tick(.12);assert(close.dead&&close.vx>450,'Deck swing should launch and finish a basic bot');assert(k.attached,'Melee threw the only deck');results.push('strong board melee');
  setup();const tough=g.spawnEnemy(200,830,'shield');tough.hp=30;g.enemies=[tough];
  for(let n=0;n<3;n++){g.fireTimer=0;k.fireInput(0,true);k.fireInput(0,false);const kind=k.attackKind;for(let i=0;i<55;i++)k.update(1/120);if(n===2)assert(kind===4,'Third connecting strike must be the finisher');}
  assert(tough.hp===6&&tough.vx>800&&k.finishers===1,'Three hit combo lacks final damage / knockback');results.push('hit-confirmed combo finisher');
  setup();k.combo=1;k.swing();for(let i=0;i<50;i++)k.update(1/120);assert(k.combo===0,'Missing a swing should reset the combo');k.launch();k.board.x=700;g.fireTimer=0;const punched=g.spawnEnemy(190,830,'gunner');punched.hp=8;g.enemies=[punched];k.fireInput(0,true);tick(.09);assert(punched.hp===6&&k.attackKind===3,'Without deck should use a weaker punch');results.push('combo miss reset / bare punches');
  setup();k.launch();k.board.x=800;const boxer=g.spawnEnemy(190,830,'shield');boxer.hp=30;g.enemies=[boxer];const steps=[],powers=[];
  for(let n=0;n<3;n++){g.fireTimer=0;k.fireInput(0,true);k.fireInput(0,false);steps.push(k.punchStep);const before=boxer.hp;for(let i=0;i<42;i++)k.update(1/120);powers.push(before-boxer.hp);}
  assert(steps.join()=== '0,1,2'&&powers.join()==='2,2,3','Boxing needs jab / cross / hook with a stronger finish');assert(boxer.vx===330&&g.player.vx===0,'Boxing hook should throw enemy without sliding Theo');for(let i=0;i<120;i++)k.update(1/120);g.fireTimer=0;k.swing();assert(k.punchStep===0,'Pause should restart at jab');k.catchBoard();assert(k.punchLife===0&&k.attack===0,'Catching the board must clear boxing pose');results.push('jab / cross / hook / combo expiry / catch cleanup');
  setup();k.mounted=true;g.player.vx=400;k.fireInput(0,true);assert(k.attack===0&&k.attached,'Riding click should not interrupt skating');results.push('riding click preserves line');
  setup();g.player.vx=360;k.mounted=true;k.mountBlend=1;g.keys.add('KeyD');g.press('Space');tick(.03);assert(g.player.vy<0&&k.attached,'Ground ollie should keep deck');g.release('Space');tick(.08);const launchY=g.player.y;g.press('Space');assert(k.airUsed&&!k.attached&&k.board.vy>500&&g.player.vy===-620,'Air kickflip did not split board / player with strong boost');g.release('Space');assert(g.player.vy===-620,'Quick release must not clip the kickflip boost');assert(!k.jump(),'Extra airborne pop should need a deck');tick(.25);assert(g.player.y<launchY-90,'Kickflip should have meaningful extra height');assert(g.player.vx===260,'Airborne without board must use normal controls');tick(1.2);k.recall();tick(.5);assert(k.attached,'Kickflip deck must remain recoverable');results.push('strong tap kickflip / responsive air control / recovery');
  setup();g.player.y=760;g.player.grounded=false;g.player.vx=260;g.coyote=0;g.wallGrace=0;g.keys.add('KeyD');k.jump();tick(1.5);assert(k.attached,'Matching the rolling board should still allow a landing catch');results.push('kickflip landing catch at running speed');
  setup();const original=k.board;k.defend();assert(!k.attached&&k.board.kind==='shield'&&k.shieldPose===.42,'Q must physically throw the deck with full-body follow-through');const shot={x:k.board.x-30,y:k.board.y,vx:-600,vy:0,life:2,hostile:true,power:1,pierce:0,boost:false,hit:new Set()};const vx=k.board.vx;assert(k.intercept(shot,{x:k.board.x+50,y:k.board.y})&&shot.life===0&&k.board.vx<vx,'Moving shield must absorb swept shots and get shoved');k.defend();assert(k.board===original&&k.shieldTosses===1,'Q while away duplicated the board');k.recall();for(let i=0;i<240&&!k.attached;i++)k.update(1/120);k.defend();assert(k.shieldTosses===2,'Q should be usable immediately after catch');results.push('physical shield / swept block / momentum / no cooldown');
  setup();k.defend();const touched=g.spawnEnemy(190,830,'shield');touched.hp=10;g.enemies=[touched];for(let i=0;i<20;i++)k.update(1/120);assert(touched.hp===8&&!k.passenger,'Shield contact should do modest damage without capturing');for(let i=0;i<600;i++)k.update(1/120);assert(Number.isFinite(k.board.x)&&k.board.y<=860&&k.board.y>800,'Shield should settle on the ground');results.push('shield contact and gravity');
  for(const angle of [0,-Math.PI/2,-Math.PI/4,Math.PI/4,Math.PI]){setup();g.player.x=180;for(let y=0;y<43;y++)g.world.set(10,y,3);g.updateAim=()=>{g.aimAngle=angle;};k.defend();assert(!k.attached,'Shield must have space to spawn next to wall');for(let i=0;i<240;i++)k.update(1/120);assert(k.board.x<200&&k.board.y>750&&k.board.y<=860,'Shield escaped through wall or floor');}results.push('shield deployment next to walls at five angles');
  setup();k.launch();const deck=k.board;k.recall();k.recall();assert(k.board===deck,'Recall replaced deck object');for(let i=0;i<240&&!k.attached;i++)k.update(1/120);assert(k.attached,'Short recall failed');k.launch();k.board.y=1100;k.update(.01);assert(k.attached,'Out-of-play deck safety failed');results.push('one persistent deck / safety recovery');
  setup();k.launch();k.board.x=820;k.board.y=810;for(let x=15;x<37;x++)for(let y=0;y<43;y++)g.world.set(x,y,3);k.recall();const destroyed=g.world.destroyed;for(let i=0;i<240&&!k.attached;i++)k.update(1/120);assert(k.attached&&k.catches===1,'Recall trapped by massive indestructible wall');assert(k.crashes===0&&g.world.destroyed===destroyed,'Recall must not generate collision/damage loops inside walls');results.push('spectral recall through massive walls');
  setup();const held=g.spawnEnemy(280,830,'gunner');g.enemies=[held];k.launch();for(let i=0;i<45&&!k.passenger;i++)k.update(1/120);assert(k.passenger===held,'Need captured bot to test cleanup');g.die();assert(!k.passenger&&!k.controls(held),'Death leaked enemy control');g.respawn();assert(g.theoKit.attached,'Respawn did not restore board');results.push('death and respawn cleanup');
  setup(2);g.modeFeedback=0;g.hud();assert(document.querySelector('#control-f').parentElement.hidden,'Unimplemented F exposed');assert(document.querySelector('#control-fire').textContent==='DECK COMBO'&&document.querySelector('.thinking-control').hidden&&document.querySelector('#control-scroll').parentElement.hidden,'Wrong Theo control labels');g.selectCharacter('tibo');g.hud();assert(!document.querySelector('#control-f').parentElement.hidden&&!document.querySelector('.thinking-control').hidden,'Switching characters did not restore controls');g.selectCharacter('theo');g.hud();g.invuln=0;g.cam=0;g.camY=440;g.render();document.querySelector('.toast').innerHTML='';results.push('HUD and roster integration');
  return results;
 });
 await page.screenshot({path:'output/playwright/theo-grip.png'});
 if(errors.length)throw Error(errors.join('\n'));return {checks:results};
 }finally{await page.unroute('**/src/main.ts*');await page.reload();}
}
