import type { Body } from "./world";
import type { Awareness } from "./perception";
export type Enemy = Body & {
  id?: number;
  flungBy?: string;
  sector?: number;
  arrival?: number;
  sheep?: number;
  combatTarget?: Body;
  awareness: Awareness;
  look: number;
  patrol: number;
  patrolWait: number;
  dash: number;
  flung: number;
  type: string;
  hp: number;
  max: number;
  face: number;
  cool: number;
  wind: number;
  hurt: number;
  dead: boolean;
  home: number;
  homeY: number;
  shield: number;
  hacked: number;
  turn: number;
  alert: boolean;
  stun: number;
  evade: number;
  lockX: number;
  lockY: number;
  voiceCool: number;
  shieldDown: number;
};
export type Bullet = {
  owner?: string;
  x: number;
  y: number;
  vx: number;
  vy: number;
  life: number;
  hostile: boolean;
  power: number;
  pierce: number;
  boost: boolean;
  tier?: number;
  color?: string;
  spell?: number;
  fireball?: number;
  hit: Set<unknown>;
};
export type Particle = {
  x: number;
  y: number;
  vx: number;
  vy: number;
  life: number;
  max: number;
  color: string;
  size: number;
  gravity: number;
};
export type Barrel = Body & {
  owner?: string;
  hp: number;
  dead: boolean;
  fuse: number;
  mobile?: boolean;
  angle?: number;
};
export type Rescue = { x: number; y: number; done: boolean };
export type Grenade = {
  owner?: string;
  x: number;
  y: number;
  vx: number;
  vy: number;
  life: number;
};
export type Relay = { x: number; y: number; done: boolean; supplied: boolean };
export type Ring = {
  x: number;
  y: number;
  r: number;
  max: number;
  life: number;
  color: string;
};
